sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: u9yoOg+3FumWd9hwZiz4cGWVO7/3T8RDFzoR2ePy0Uhn/mKtpV5CCy+aM52/lkSwA2qD1FSNEiGec1G/TCHrgtSF6/SvIjgwLVVpsOPLzikDZ5J0ISQaNx0sdoUXnXs9iCLmYfS8STSblMHinQgoN2vVGS3QEMZd+0/kBaLcJjUX1h0zH2LpnLGrY75F4BcQWlm4W6szX6MQN/CFBRRhurgsOYKUAC3IN5deZyAsMuTBGIszehfwQnA88Wh4okGmNZ6UnKHL59Agzo3X+fu0PwWvjOdGvnP981HN/OFPNmO7tkDcIhdYqDTQ34vIsVjk0Kakcf62JSWfUEPKjj1D/PpE5QOBUcB/ecXi2VzHbC7xk8Ufnr1h8oif3wj+HL5GL6+TggPEpYyZY2wWbd/+3VzXCIdyXcEFUEI9pBkUO/CLXrYgQuQ5868SmlfQZE6CuzJHwktkFwRAQSoEiX2Ay3CWY24f5eE/nXHZY5M7eACY4cn9szxDuxIH6AAvtW3EyYbRtbKn1bUPht7i97+S9icMw9436kTy0A1YseimfcDljtEkVDkB1rrN8QlYa+FWh4+e3MdKh4aRR3tIoea4lMKGEiFKKRpQVUumB78CtMnm7E4K/+CPsvwy7JqiHcABSlBkROG9vfsEfWX5G+SUXxFE7ZUQv8UZiNRCMZzIDrY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Phaedo_1658
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy